---
- name: 'Use uri module to call https://anapioficeandfire.com/api/'   # metadata
  hosts: localhost                   # this is a *multiplier* (how many instances of the playbook should be created)
  gather_facts: false                # this would only define ansible_facts for the localhost (i.e. the controller)
  connection: ansible.builtin.local  # ensure ansible does not ssh to itself
  
  tasks:
 
    - name: 'Make api call to https://anapioficeandfire.com/api/'
      ansible.builtin.uri:
        url: 'https://anapioficeandfire.com/api/'
        method: GET                  # default is GET
      register: results              # create the variable 'results' and save the 200 + JSON response from server

    - name: Display the content of results
      ansible.builtin.debug:
        var: results.json            # no HTTP headers or other metadata displayed, just the JSON attachment

    - name: "Make api call to {{ results.json.books }}"
      ansible.builtin.uri:
        url: "{{ results.json.books }}"   # keeping the code DRY (DON'T REPEAT YOURSELF)
        method: GET                       # default is GET
      register: bookresults               # create the variable 'results' and save the 200 + JSON response from server

    - name: Display the content of results
      ansible.builtin.debug:
        var: bookresults.json            # no HTTP headers or other metadata displayed, just the JSON attachment

    - name: "Make api call to {{ results.json.characters }}"
      ansible.builtin.uri:
        url: "{{ results.json.characters }}"  # keeping the code DRY (DON'T REPEAT YOURSELF)
        method: GET                           # default is GET
      register: characterresults              # create the variable 'results' and save the 200 + JSON response from server
        
    - name: Display the content of results
      ansible.builtin.debug:
        var: characterresults.json            # no HTTP headers or other metadata displayed, just the JSON attachment

    - name: "Make api call to {{ results.json.houses }}"
      ansible.builtin.uri:
        url: "{{ results.json.houses }}"      # keeping the code DRY (DON'T REPEAT YOURSELF)
        method: GET                           # default is GET
      register: houseresults                  # create the variable 'results' and save the 200 + JSON response from server
        
    - name: Display the content of results
      ansible.builtin.debug:
        var: houseresults.json                # no HTTP headers or other metadata displayed, just the JSON attachment
